[package]
name = "cube_shuffle-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
parse-display = "0.5.3"

[dev-dependencies]
proptest = "1.0.0"